@startuml
'https://plantuml.com/class-diagram

interface DomainObject {
    ID getId();
    boolean isNew();
}

abstract class AbstractDomainObject {
}

DomainObject <|-- AbstractDomainObject

interface AggregateRoot {
    boolean isDeleted();
}

abstract class AbstractAggregateRoot {

}

AggregateRoot <|-- AbstractAggregateRoot

AbstractDomainObject <|-- AbstractAggregateRoot

abstract class AbstractSimpleDomainObject

AbstractDomainObject <|-- AbstractSimpleDomainObject


abstract class AbstractSimpleAggregateRoot

AbstractAggregateRoot <|-- AbstractSimpleAggregateRoot

@enduml